// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ExtractContentData, ExtractContentErrors, ExtractContentResponses, SearchWebData, SearchWebErrors, SearchWebResponses, WriteLanguageData, WriteLanguageErrors, WriteLanguageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * ## Extract structured content and cite from any URL
 *
 * ![Extractor](https://i.imgur.com/o8NTXxY.png)
 *
 * ### 🚜📜 Tractor the Text Extractor
 * 1. Main Content Detection: Extract the main content from a URL by combining
 * Mozilla Readability and Postlight Mercury algorithms, utilizing over 100
 * custom adapters for major sites for article, author, date HTML classes.
 * 2. Basic HTML Standardization: Transform complex HTML into a simplified
 * reading-mode format of basic HTML, making it ideal for research note archival
 * and focused reading, with headings, images and links.
 * 3. YouTube Transcript Processing: When a YouTube video URL is detected,
 * retrieve the complete video transcript including both manual captions and
 * auto-generated subtitles, maintaining proper timestamp synchronization and
 * speaker identification where available.
 * 4. PDF to HTML: Process PDF documents by extracting
 * formatted text while intelligently handling line breaks, page headers,
 * footnotes. The system analyzes text height statistics to automatically
 * infer heading levels, creating a properly structured document hierarchy
 * based on standard deviation from mean text size.
 * 5. Citation Information Extraction: Identify and extract citation metadata
 * including author names, publication dates, sources, and titles using HTML
 * meta tags and common class name patterns. The system validates author names
 * against a comprehensive database of 90,000 first and last names,
 * distinguishing between personal and organizational authors to properly
 * format citations.
 * 6. Author Name Formatting: Process author names by checking against
 * known name databases, handling affixes and titles correctly, and determining
 * whether to reverse the name order based on whether it's a personal or
 * organizational author, ensuring proper citation formatting.
 *
 */
export const extractContent = <ThrowOnError extends boolean = false>(options: Options<ExtractContentData, ThrowOnError>) => (options.client ?? client).get<ExtractContentResponses, ExtractContentErrors, ThrowOnError>({ url: '/extract', ...options });

/**
 * ## Generate language model reply using agent prompts
 *
 *
 * - ❓ **Inputs**: 👄 Language Intelligence Provider, 🔑 API Key,  🤖 agent template name, 🧠 model name and options,
 * and 🆎 context variables for that agent
 * - 🤖 **Agent Instruction Templates**: [LangHub](https://smith.langchain.com/hub) template or custom:
 * question(query, chat_history), summarize-bullets(article), summarize(article),
 * suggest-followups(chat_history, article), answer-cite-sources(context, chat_history, query),
 * query-resolution(chat_history, query), knowledge-graph-nodes(query, article),
 * summary-longtext(summaries)
 * - 🧠 **How Language Models Work**: Language models learn from billions of text examples to
 * identify statistical patterns and structures across diverse sources, converting words into
 * high-dimensional vectors—numerical lists that capture meaning and relationships between concepts.
 * These mathematical representations allow models to understand that "king/queen" share properties
 * and "Paris/France" mirrors "Tokyo/Japan" through their transformer architecture, a neural network
 * backbone that processes information through multiple layers of analysis. The attention mechanism
 * enables the system to dynamically focus on relevant parts of input text when generating each word,
 * maintaining context like humans tracking conversation threads, while calculating probability scores
 * across the entire vocabulary for each word position based on processed context. Rather than retrieving
 * stored responses, models create novel text by selecting the most probable words given learned
 * patterns, maintaining coherence across long passages while adapting to specific prompt nuances
 * through deep pattern recognition.
 * **Self-Attention**: Each word creates three representations: Query (what it's looking for), Key (what
 * it offers), and Value (its actual content). For example, in "The cat sat on the mat," the word "cat"
 * has a Query vector that searches for actions, a Key vector that advertises itself as a subject, and
 * a Value vector containing its semantic meaning as an animal. The attention mechanism calculates how
 * much "cat" should focus on other words by comparing its Query with their Keys - finding high
 * similarity with "sat" (the action) - then combines the corresponding Value vectors to create a
 * contextualized representation where "cat" now understands it's the one doing the sitting.
 *
 * - 📚 **Learning Resources**:
 * [LLM Training Example](https://github.com/vtempest/ai-research-agent/blob/master/packages/neural-net/src/train/predict-next-word.js),
 * [LangChain ReactAgent Tools](https://medium.com/@terrycho/how-langchain-agent-works-internally-trace-by-using-langsmith-df23766e7fb4),
 * [Hugging Face Tutorials](https://huggingface.co/learn), [OpenAI Cookbook](https://cookbook.openai.com),
 * [Transformer Overview](https://jalammar.github.io/illustrated-transformer/),
 * [Building Transformer Guide](https://www.datacamp.com/tutorial/building-a-transformer-with-py-torch),
 * [PyTorch Overview](https://www.learnpytorch.io/pytorch_cheatsheet/)
 *
 * ### 👄  Language Intelligence Providers (LIPs)
 *
 * | Provider | 🌍 | Top Model (Others) | 🏆 Benchmarks | 📄 Docs | 🔑 Keys | 💰 Funding |
 * |---|---|---|---|---|---|---|
 * | **Anthropic** | 🇺🇸 | Claude Mythos / Opus 4.7 (Sonnet, Haiku) | 🥇 GPQA Diamond 94.6% · 🥇 SWE-bench 93.9% · 🧬 PhD reasoning | [Docs](https://docs.anthropic.com/en/docs/welcome) | [Keys](https://console.anthropic.com/settings/keys) | ~$60B |
 * | **OpenAI** | 🇺🇸 | GPT-5.2 / o3 / Codex (o1, o4, o4-mini, gpt-4o) | 🥇 AIME 2025 100% · 🥇 SWE-bench Pro · 📚 MMLU-Pro 90% | [Docs](https://platform.openai.com/docs/overview) | [Keys](https://platform.openai.com/api-keys) | ~$180B |
 * | **Google Gemini** | 🇺🇸 | Gemini 3.1 Pro (Flash, Flash-Lite, Gemma) | 🥇 GPQA 94.1% · 🥇 LiveCodeBench Elo 2439 · 🌐 #1 in 6/13 Vals | [Docs](https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models) | [Keys](https://cloud.google.com/vertex-ai/generative-ai/docs/start/express-mode/overview#api-keys) | Public |
 * | **xAI** | 🇺🇸 | Grok-4 Heavy (Grok-3, Grok Vision) | 🥇 AIME 2025 100% · 🧮 Math competition · ⚡ X integration | [Docs](https://docs.x.ai/docs#models) | [Keys](https://console.x.ai/) | ~$45B |
 * | **Meta** | 🇺🇸 | Llama 4 Maverick / Scout (Llama 3.x, CodeLlama) | 🥇 DocVQA 94.4% · 🥇 10M token context · 📊 ChartQA 90% | [Docs](https://www.llama.com/docs/overview/) | [Keys](https://www.llama.com/llama-downloads/) | Public |
 * | **NVIDIA** | 🇺🇸 | Nemotron-Cascade 2 (Llama Nemotron, Minitron) | 🥇 LCB v6 87.2% · 🏅 IMO+IOI+ICPC gold · 🧮 AIME 98.6% | [Docs](https://docs.api.nvidia.com/nim/reference/llm-apis) | [Keys](https://build.nvidia.com/settings/api-keys) | Public |
 * | **Perplexity AI** | 🇺🇸 | Sonar Reasoning Pro (Sonar, Sonar Deep Research) | 🥇 Search Arena · 🔍 #1 web-grounded QA · 🌐 Real-time retrieval | [Docs](https://docs.perplexity.ai/models/model-cards) | [Keys](https://www.perplexity.ai/account/api/keys) | ~$1B |
 * | **Groq** | 🇺🇸 | (Llama, DeepSeek, Gemma, Mistral, Qwen) | ⚡ #1 inference speed · 🏎️ Fastest TTFT · 🔧 LPU hardware | [Docs](https://console.groq.com/docs/overview) | [Keys](https://console.groq.com/keys) | ~$640M |
 * | **Mistral AI** | 🇫🇷 | Mistral Large 3 (Small 4, Codestral, Devstral, Pixtral) | 🥈 Arena Elo 1418 · 🌍 Multilingual MMLU 85.5% · 🚀 Fastest TTFT | [Docs](https://docs.mistral.ai/) | [Keys](https://console.mistral.ai/api-keys/) | ~$3.1B |
 * | **Together AI** | 🇺🇸 | (Llama, Mistral, Qwen, Gemma, DeepSeek, Hermes) | 🏗️ Widest open hosting · 💸 Best open-source pricing · 🔧 Fine-tuning | [Docs](https://docs.together.ai/docs/quickstart) | [Keys](https://api.together.xyz/settings/api-keys) | ~$225M |
 * | **Moonshot AI (Kimi)** | 🇨🇳 | Kimi K2.5 Reasoning (K2.6, K2) | 🥇 AIME open 96.1% · 🥇 MATH-500 98% · 🥇 HumanEval 99% | [Docs](https://platform.moonshot.cn/docs) | [Keys](https://platform.moonshot.cn/console/api-keys) | ~$3.9B |
 * | **Zhipu AI (GLM)** | 🇨🇳 | GLM-5 Reasoning / GLM-4.7 (GLM-4V, CogView) | 🥇 Chatbot Arena Elo 1451 · 🥇 MMLU 96% · 🧮 AIME 95.7% | [Docs](https://bigmodel.cn/dev/api) | [Keys](https://bigmodel.cn/usercenter/apikeys) | ~$1.8B |
 * | **Alibaba (Qwen)** | 🇨🇳 | Qwen3-Coder / Qwen3-235B (QwQ, Qwen-VL, Qwen-Audio) | 🥇 Codeforces Elo 2056 · 💻 SWE-bench 69.6% · 🏎️ LCB 70.7% | [Docs](https://www.alibabacloud.com/help/en/model-studio/developer-reference/use-qwen-by-calling-api) | [Keys](https://bailian.console.aliyun.com/?apiKey=1) | Public |
 * | **DeepSeek** | 🇨🇳 | DeepSeek V3.2 / R1 (DeepSeek-Coder, DeepSeek-VL) | 🥇 IMO gold (open) · 📚 MMLU-Pro 81.2 · 🧮 AIME 87.5% | [Docs](https://api-docs.deepseek.com/) | [Keys](https://platform.deepseek.com/api_keys) | Bootstrapped |
 * | **Cloudflare** | 🇺🇸 | (Llama, Gemma, Mistral, Phi, Qwen, DeepSeek) | 🌐 Edge inference · ⚡ Serverless CDN scale · 🔒 Privacy-first | [Docs](https://developers.cloudflare.com/workers-ai/) | [Keys](https://dash.cloudflare.com/profile/api-tokens) | Public |
 *
 * ![how_transformer_works](https://i.imgur.com/l0BvtlG.jpeg)
 * ![agent_arch_viz](https://i.imgur.com/bailW5n.gif)
 * ![agent_arch_viz2](https://i.imgur.com/uW6E9VJ.gif)
 *
 */
export const writeLanguage = <ThrowOnError extends boolean = false>(options: Options<WriteLanguageData, ThrowOnError>) => (options.client ?? client).post<WriteLanguageResponses, WriteLanguageErrors, ThrowOnError>({
    url: '/agents',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * ## Search the web
 *
 * ![AILogo](https://i.imgur.com/yYMTcTX.png)
 *
 * Search the web by sending a query via SearXNG metasearch engine of 100+ sources.
 * You can specify the type of content you want—such as general web results,
 * news articles, videos, images, science topics, files, or IT-related
 * information—by choosing the appropriate category.
 * Additional filters let you narrow results by recency (like results
 * from the past day, week, month, or year), language, and page number.
 * The API returns a structured list of results, each including a title, URL, snippet, domain, and other useful details, making it easy to display or analyze the information. This flexible and robust search tool is ideal for apps, research projects, and any situation where up-to-date, diverse web data is needed.
 * [Searxng Overview](https://medium.com/@elmo92/search-in-peace-with-searxng-an-alternative-search-engine-that-keeps-your-searches-private-accd8cddd6fc)
 *
 * **Web Search Stats**:
 * Google processses 90% of Web Search, 13.6 billion searches every day—almost 5 trillion per year.
 * Its search index exceeds 100,000,000 GB and covers 130 trillion pages.
 * Ranking uses over 200 factors, including keyword relevance, backlinks, page speed, and user experience; the top organic result gets about 22% of clicks, and ads allow monetizing keyword traffic.
 *
 */
export const searchWeb = <ThrowOnError extends boolean = false>(options: Options<SearchWebData, ThrowOnError>) => (options.client ?? client).get<SearchWebResponses, SearchWebErrors, ThrowOnError>({ url: '/search', ...options });
